app: f1-predictor
service: f1-prediction-api-flask

frameworkVersion: '2 || 3'

custom:
  wsgi:
      app: app.app
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"
    warmup:
    events:
      - schedule: "rate(5 minutes)"
    timeout: 50    

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/pytorch_model.bin
    - raw/**
    - .vscode/**
    - .ipynb_checkpoints/**
