# Pre-process and model building
name: Python application

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f ./flask-api/requirements.txt ]; then pip install -r ./flask-api/requirements.txt; fi
    - name: Python scripts => Ergast to MongoDB
      if: ${{ false }}
      env:
        MONGO_DB_USER: ${{secrets.MONGO_DB_USER}}
        MONGO_DB_PW: ${{secrets.MONGO_DB_PW}}
      run: |
        python './scripts/ergast-to-mongo.py'
    - name: Python scripts => Creating csv results from MongoDB
      if: ${{ false }}
      env:
        MONGO_DB_USER: ${{secrets.MONGO_DB_USER}}
        MONGO_DB_PW: ${{secrets.MONGO_DB_PW}}
      run: |
        python './scripts/create-csv-from-mongo.py'
    - name: Python scripts => Feature Engineering
      if: ${{ false }}
      run: |
        python './scripts/feature-engineering.py'
    - name: Python scripts => Machine Learning Model Building
      if: ${{ false }}
      run: |
        python './scripts/build-ml-model.py'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Serverless WSGI
      run: sls plugin install -n serverless-wsgi
    - name: Deploy model and API
      run: npm run deploy
      working-directory: ./flask-api
