# Pre-process and model building
name: F1 Prediction MLOps (Docker)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest from source control
      uses: actions/checkout@v2
      
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PW }}
        image: jaeyow/f1_predictor:latest
        options: -e MONGO_DB_USER=${{secrets.MONGO_DB_USER}} -e MONGO_DB_PW=${{secrets.MONGO_DB_PW}} -e AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY}} -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET}}
        run: |
          python "./scripts/a_ergast_to_mongo.py"
          python "./scripts/b_create_csv_from_mongo.py"
          python "./scripts/c_feature_engineering"
          python "./scripts/d_build_ml_model"
          cd flask-api
          npm run deploy
          
    
